Repository codersforcauses/p2s-backend, pull requests merged in 2019-02, with the labels that each got.

#111 Jezz yarn update
  .travis.yml
  Dockerfile
  package.json
  src/seeder.js
Labels: Important

#112 Added git hooks to the backend
  .travis.yml
  package.json
Labels: enhancement

#108 Merging seeder into master
  .gitignore
  .travis.yml
  Dockerfile
  package.json
  src/app.js
  src/channels.js
  src/index.js
  src/models/regions.model.js
  src/models/schools.model.js
  src/models/users.model.js
  src/seeder.js
  src/services/index.js
  src/services/schools/schools.hooks.js
  src/services/students/students.hooks.js
  src/services/users/admin.hooks.js
  src/services/users/coach.hooks.js
  src/services/users/manager.hooks.js
  src/services/users/users.hooks.js
Labels: Important

#116 User hook permissions fixed
  src/services/users/users.hooks.js
Labels: critical

#126 Dev
  package.json
  src/hooks/userhooks.js
  src/models/programs.model.js
  src/models/users.model.js
  src/seeder.js
  src/services/users/coach.hooks.js
  src/services/users/manager.hooks.js
  src/services/users/users.hooks.js
Labels: enhancement

#127 Hook permissions and update blocking
  src/app.hooks.js
  src/services/activities/activities.hooks.js
  src/services/feedback/feedback.hooks.js
  src/services/matrix/matrix.hooks.js
  src/services/programs/programs.hooks.js
  src/services/regions/regions.hooks.js
  src/services/reports/reports.hooks.js
  src/services/schools/schools.hooks.js
  src/services/sessions/sessions.hooks.js
  src/services/students/students.hooks.js
  src/services/users/coach.hooks.js
  src/services/users/manager.hooks.js
  src/services/users/users.hooks.js
Labels: enhancement
